#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Kleinrotti <kleinrotti@saltcloud.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def agent_mirth_arguments(params, hostname, ipaddress):
    args = []
    args += ['-i', ipaddress or hostname]
    args += ['-u', params['username']]
    args += ['-s', params['secret']]
    args += ['-p', params['port']]
    args += ['-l', params['log_fetch_size']]
    if "log_services" not in params:
        args += ['-ls']
    if "verify_ssl" in params:
        args += ['-v']
    return args


special_agent_info['mirth'] = agent_mirth_arguments
